<?php

namespace Siciarek\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChatChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatChannelRepository extends EntityRepository
{
}
