services:

    chat.message:
        class: Siciarek\ChatBundle\Model\ChatMessage
        calls:
            - [ setContainer, [ '@service_container' ] ]

    chat.channel:
        class: Siciarek\ChatBundle\Model\ChatChannel
        calls:
            - [ setContainer, [ '@service_container' ] ]
        
