<?php

namespace Siciarek\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChatChannelAssigneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatChannelAssigneRepository extends EntityRepository
{
}
